import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';

class HomeScreen extends StatelessWidget {
  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          backgroundColor: Colors.yellow,
          leading: Text("I'M LEADING"),
          title: Text("My First Ludo board UI"),
          actions: [
            Text("8th June 2024"),
          ],
        ),
        //body: Center(child: Container(alignment: Alignment.center, height: 100, width: 100, color: Colors.amber,))
        body: Center(
          child: SingleChildScrollView(
            child: Column(children:
            [Row(children: [
                    Container(decoration: BoxDecoration(color:Colors.green,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.green,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.green,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.green,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.green,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.green,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.white,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.white,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.white,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.yellow,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.yellow,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.yellow,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.yellow,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.yellow,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.yellow,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                           ],),
            
            Row(children: [
            Container(decoration: BoxDecoration(color:Colors.green,border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 2, 53, 4),border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 2, 53, 4),border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 2, 53, 4),border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 2, 53, 4),border: Border.all(color:Colors.black)),height: 50, width: 50,),
             Container(decoration: BoxDecoration(color:Colors.green,border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:Colors.white,border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:Colors.white,border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:Colors.white,border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:Colors.yellow,border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:Color.fromARGB(255, 204, 124, 32),border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:Color.fromARGB(255, 204, 124, 32),border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:Color.fromARGB(255, 204, 124, 32),border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:Color.fromARGB(255, 204, 124, 32),border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.yellow,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    ],),
            
            Row(children: [
            Container(decoration: BoxDecoration(color:Colors.green,border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 2, 53, 4),border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 2, 53, 4),border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 2, 53, 4),border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 2, 53, 4),border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:Colors.green,border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:Colors.white,border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:Color.fromARGB(255, 204, 124, 32),border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:Color.fromARGB(255, 204, 124, 32),border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:Colors.yellow,border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:Color.fromARGB(255, 204, 124, 32),border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:Color.fromARGB(255, 204, 124, 32),border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:Color.fromARGB(255, 204, 124, 32),border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:Color.fromARGB(255, 204, 124, 32),border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:Colors.yellow,border: Border.all(color:Colors.black)),height: 50, width: 50,),
              ],),
            
            Row(children: [
            Container(decoration: BoxDecoration(color:Colors.green,border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 2, 53, 4),border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 2, 53, 4),border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 2, 53, 4),border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 2, 53, 4),border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:Colors.green,border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 65, 63, 63),border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:Color.fromARGB(255, 204, 124, 32),border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:Colors.white,border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:Colors.yellow,border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:Color.fromARGB(255, 204, 124, 32),border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:Color.fromARGB(255, 204, 124, 32),border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:Color.fromARGB(255, 204, 124, 32),border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:Color.fromARGB(255, 204, 124, 32),border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:Colors.yellow,border: Border.all(color:Colors.black)),height: 50, width: 50,),
            ],),
            
            Row(children: [
            Container(decoration: BoxDecoration(color:Colors.green,border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 2, 53, 4),border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 2, 53, 4),border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 2, 53, 4),border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 2, 53, 4),border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:Colors.green,border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:Colors.white,border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:Color.fromARGB(255, 204, 124, 32),border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:Colors.white,border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:Colors.yellow,border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:Color.fromARGB(255, 204, 124, 32),border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:Color.fromARGB(255, 204, 124, 32),border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:Color.fromARGB(255, 204, 124, 32),border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:Color.fromARGB(255, 204, 124, 32),border: Border.all(color:Colors.black)),height: 50, width: 50,),
            Container(decoration: BoxDecoration(color:Colors.yellow,border: Border.all(color:Colors.black)),height: 50, width: 50,),
              ],),
            
            Row(children: [
                    Container(decoration: BoxDecoration(color:Colors.green,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.green,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.green,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.green,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.green,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.green,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.white,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Color.fromARGB(255, 204, 124, 32),border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.white,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.yellow,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.yellow,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.yellow,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.yellow,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.yellow,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.yellow,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                           ],),
            Row(children: [
                    Container(decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black)),height: 50,width: 50,),
                    Container(decoration: BoxDecoration(color: const Color.fromARGB(255, 2, 53, 4),border: Border.all(color: Colors.black)),height: 50,width: 50,),
                    Container(decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black)),height: 50,width: 50,),
                    Container(decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black)),height: 50,width: 50,),
                    Container(decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black)),height: 50,width: 50,),
                    Container(decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black)),height: 50,width: 50,),
                    Container(decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black)),height: 50,width: 50,),
                    Container(decoration: BoxDecoration(color: Color.fromARGB(255, 204, 124, 32),border: Border.all(color: Colors.black)),height: 50,width: 50,),
                    Container(decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black)),height: 50,width: 50,),
                    Container(decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black)),height: 50,width: 50,),
                    Container(decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black)),height: 50,width: 50,),
                    Container(decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black)),height: 50,width: 50,),
                    Container(decoration: BoxDecoration(color: Color.fromARGB(255, 51, 49, 49),border: Border.all(color: Colors.black)),height: 50,width: 50,),
                    Container(decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black)),height: 50,width: 50,),
                    Container(decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black)),height: 50,width: 50,),
                    ],),        
                    
            Row(children: [
                    Container(decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black)),height: 50,width: 50,),
                    Container(decoration: BoxDecoration(color: const Color.fromARGB(255, 2, 53, 4),border: Border.all(color: Colors.black)),height: 50,width: 50,),
                    Container(decoration: BoxDecoration(color: const Color.fromARGB(255, 2, 53, 4),border: Border.all(color: Colors.black)),height: 50,width: 50,),
                    Container(decoration: BoxDecoration(color: const Color.fromARGB(255, 2, 53, 4),border: Border.all(color: Colors.black)),height: 50,width: 50,),
                    Container(decoration: BoxDecoration(color: const Color.fromARGB(255, 2, 53, 4),border: Border.all(color: Colors.black)),height: 50,width: 50,),
                    Container(decoration: BoxDecoration(color: const Color.fromARGB(255, 2, 53, 4),border: Border.all(color: Colors.black)),height: 50,width: 50,),
                    Container(decoration: BoxDecoration(color: const Color.fromARGB(255, 2, 53, 4),border: Border.all(color: Colors.black)),height: 50,width: 50,),
                    Container(decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black)),height: 50,width: 50,),
                    Container(decoration: BoxDecoration(color: const Color.fromARGB(255, 11, 47, 77),border: Border.all(color: Colors.black)),height: 50,width: 50,),
                    Container(decoration: BoxDecoration(color: const Color.fromARGB(255, 11, 47, 77),border: Border.all(color: Colors.black)),height: 50,width: 50,),
                    Container(decoration: BoxDecoration(color: const Color.fromARGB(255, 11, 47, 77),border: Border.all(color: Colors.black)),height: 50,width: 50,),
                    Container(decoration: BoxDecoration(color: const Color.fromARGB(255, 11, 47, 77),border: Border.all(color: Colors.black)),height: 50,width: 50,),
                    Container(decoration: BoxDecoration(color: const Color.fromARGB(255, 11, 47, 77),border: Border.all(color: Colors.black)),height: 50,width: 50,),
                    Container(decoration: BoxDecoration(color: const Color.fromARGB(255, 11, 47, 77),border: Border.all(color: Colors.black)),height: 50,width: 50,),
                    Container(decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black)),height: 50,width: 50,),
                    ],),        
            
            Row(children: [
                    Container(decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black)),height: 50,width: 50,),
                    Container(decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black)),height: 50,width: 50,),
                    Container(decoration: BoxDecoration(color: Color.fromARGB(255, 51, 50, 50),border: Border.all(color: Colors.black)),height: 50,width: 50,),
                    Container(decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black)),height: 50,width: 50,),
                    Container(decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black)),height: 50,width: 50,),
                    Container(decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black)),height: 50,width: 50,),
                    Container(decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black)),height: 50,width: 50,),
                    Container(decoration: BoxDecoration(color: const Color.fromARGB(255, 100, 8, 2),border: Border.all(color: Colors.black)),height: 50,width: 50,),
                    Container(decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black)),height: 50,width: 50,),
                    Container(decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black)),height: 50,width: 50,),
                    Container(decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black)),height: 50,width: 50,),
                    Container(decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black)),height: 50,width: 50,),
                    Container(decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black)),height: 50,width: 50,),
                    Container(decoration: BoxDecoration(color: const Color.fromARGB(255, 11, 47, 77),border: Border.all(color: Colors.black)),height: 50,width: 50,),
                    Container(decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black)),height: 50,width: 50,),
                    ],),      
            
            Row(children: [
                    Container(decoration: BoxDecoration(color:Colors.red,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.red,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.red,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.red,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.red,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.red,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.white,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 100, 8, 2),border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.white,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.blue,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.blue,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.blue,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.blue,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.blue,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.blue,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                           ],),
            Row(children: [
                    Container(decoration: BoxDecoration(color:Colors.red,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 100, 8, 2),border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 100, 8, 2),border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 100, 8, 2),border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 100, 8, 2),border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.red,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.white,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 100, 8, 2),border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.white,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.blue,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 11, 47, 77),border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 11, 47, 77),border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 11, 47, 77),border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 11, 47, 77),border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.blue,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                           ],),
                       Row(children: [
                    Container(decoration: BoxDecoration(color:Colors.red,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 100, 8, 2),border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 100, 8, 2),border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 100, 8, 2),border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 100, 8, 2),border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.red,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.white,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 100, 8, 2),border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.white,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.blue,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 11, 47, 77),border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 11, 47, 77),border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 11, 47, 77),border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 11, 47, 77),border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.blue,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                           ],),
                                      Row(children: [
                    Container(decoration: BoxDecoration(color:Colors.red,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 100, 8, 2),border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 100, 8, 2),border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 100, 8, 2),border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 100, 8, 2),border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.red,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.white,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 100, 8, 2),border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 58, 55, 55),border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.blue,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 11, 47, 77),border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 11, 47, 77),border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 11, 47, 77),border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 11, 47, 77),border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.blue,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                           ],),
                                      Row(children: [
                    Container(decoration: BoxDecoration(color:Colors.red,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 100, 8, 2),border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 100, 8, 2),border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 100, 8, 2),border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 100, 8, 2),border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.red,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 100, 8, 2),border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 100, 8, 2),border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.white,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.blue,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 11, 47, 77),border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 11, 47, 77),border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 11, 47, 77),border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:const Color.fromARGB(255, 11, 47, 77),border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.blue,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                           ],),
            
            
            
            Row(children: [
                    Container(decoration: BoxDecoration(color:Colors.red,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.red,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.red,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.red,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.red,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.red,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.white,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.white,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.white,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.blue,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.blue,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.blue,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.blue,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.blue,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                    Container(decoration: BoxDecoration(color:Colors.blue,border: Border.all(color:Colors.black)),height: 50, width: 50,),
                           ],),
            
                    ],        
                 
                  ),
          )
    )
    );
  }
}